// components/admin/CategoryForm.tsx
import React, { useState } from 'react';
import {
  View,
  Text,
  StyleSheet,
  TextInput,
  TouchableOpacity,
  Alert,
  ActivityIndicator,
  ScrollView,
  Dimensions,
} from 'react-native';
import { Feather } from '@expo/vector-icons';
import { LinearGradient } from 'expo-linear-gradient';
import { ImageUploader } from './ImageUploader';

const { width } = Dimensions.get('window');

// Dark Blue Theme Colors
const C = {
  bg: '#060B1F',
  surface: '#0D1535',
  surfaceAlt: '#111C42',
  border: '#1E2D60',
  blue1: '#1565C0',
  blue2: '#1976D2',
  blue3: '#42A5F5',
  blue4: '#90CAF9',
  cyan: '#00E5FF',
  purple: '#7C4DFF',
  indigo: '#3D5AFE',
  accentGreen: '#00E676',
  accentOrange: '#FFB300',
  accentRed: '#FF5252',
  textPrimary: '#E8EAF6',
  textSecondary: '#9FA8DA',
  textMuted: '#4A5580',
  white: '#FFFFFF',
};

// Bubble Component
const Bubble = ({ size, top, bottom, left, right, opacity = 0.12, color = C.blue3 }: any) => (
  <View style={{
    position: 'absolute',
    width: size,
    height: size,
    borderRadius: size / 2,
    backgroundColor: color,
    opacity,
    top, bottom, left, right,
  }} />
);

// Glow Ring Component
const GlowRing = ({ size, top, bottom, left, right, opacity = 0.18, color = C.cyan }: any) => (
  <View style={{
    position: 'absolute',
    width: size,
    height: size,
    borderRadius: size / 2,
    borderWidth: 1.5,
    borderColor: color,
    opacity,
    top, bottom, left, right,
  }} />
);

interface CategoryFormProps {
  initialData?: { 
    $id?: string; 
    name: string; 
    slug: string; 
    image?: string;
    productCount?: number;
  };
  onSubmit: (data: { name: string; slug: string; image?: string }, imageFile?: any) => Promise<void>;
  onCancel: () => void;
  loading?: boolean;
}

export const CategoryForm: React.FC<CategoryFormProps> = ({
  initialData,
  onSubmit,
  onCancel,
  loading = false,
}) => {
  const [name, setName] = useState(initialData?.name || '');
  const [slug, setSlug] = useState(initialData?.slug || '');
  const [images, setImages] = useState<string[]>(initialData?.image ? [initialData.image] : []);
  const [focusedInput, setFocusedInput] = useState<string | null>(null);
  const [slugAutoGenerated, setSlugAutoGenerated] = useState(!initialData);

  const generateSlug = (text: string) => {
    return text
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/^-|-$/g, '');
  };

  const handleNameChange = (text: string) => {
    setName(text);
    if (slugAutoGenerated && !initialData) {
      setSlug(generateSlug(text));
    }
  };

  const handleSlugChange = (text: string) => {
    setSlug(generateSlug(text));
    setSlugAutoGenerated(false);
  };

  const handleSlugAuto = () => {
    setSlug(generateSlug(name));
    setSlugAutoGenerated(true);
  };

  const handleSubmit = async () => {
    if (!name.trim()) {
      Alert.alert('Error', 'Category name is required');
      return;
    }
    if (!slug.trim()) {
      Alert.alert('Error', 'Slug is required');
      return;
    }

    await onSubmit({ name: name.trim(), slug: slug.trim(), image: images[0] }, undefined);
  };

  const getInputStyle = (fieldName: string) => [
    styles.input,
    focusedInput === fieldName && styles.inputFocused,
  ];

  const isEditing = !!initialData;

  return (
    <ScrollView 
      style={styles.container}
      showsVerticalScrollIndicator={false}
      contentContainerStyle={styles.contentContainer}
    >
      {/* Bubbles Decoration */}
      <Bubble size={160} top={-50} right={-40} opacity={0.08} />
      <Bubble size={110} bottom={-35} left={-30} opacity={0.1} color={C.purple} />
      <Bubble size={70} top={100} right={35} opacity={0.12} color={C.cyan} />
      <Bubble size={45} bottom={80} right={60} opacity={0.15} color={C.indigo} />
      <Bubble size={28} top={180} left={25} opacity={0.18} color={C.cyan} />
      <Bubble size={16} bottom={250} left={100} opacity={0.22} color={C.white} />
      <GlowRing size={170} top={-55} right={-45} opacity={0.12} />
      <GlowRing size={120} bottom={-40} left={-35} color={C.purple} />
      <GlowRing size={75} top={95} right={30} color={C.blue4} />

      {/* Header Section */}
      <LinearGradient
        colors={['#0A1647', '#0D1F6E', '#1034A6']}
        start={{ x: 0, y: 0 }}
        end={{ x: 1, y: 1 }}
        style={styles.header}
      >
        <View style={styles.headerIcon}>
          <Feather name="folder" size={28} color={C.cyan} />
        </View>
        <Text style={styles.title}>
          {isEditing ? '✏️ Edit Category' : '📁 Add New Category'}
        </Text>
        <Text style={styles.subtitle}>
          {isEditing 
            ? 'Update your existing category details' 
            : 'Create a new product category for your store'}
        </Text>
        
        {isEditing && initialData?.productCount !== undefined && (
          <View style={styles.infoBadge}>
            <Feather name="package" size={14} color={C.cyan} />
            <Text style={styles.infoBadgeText}>
              {initialData.productCount} products in this category
            </Text>
          </View>
        )}
      </LinearGradient>

      {/* Form Section */}
      <View style={styles.formSection}>
        {/* Category Name */}
        <View style={styles.inputGroup}>
          <View style={styles.labelContainer}>
            <Feather name="tag" size={16} color={C.cyan} />
            <Text style={styles.label}>Category Name *</Text>
          </View>
          <TextInput
            style={getInputStyle('name')}
            placeholder="e.g., Men's Fashion"
            placeholderTextColor={C.textMuted}
            value={name}
            onChangeText={handleNameChange}
            onFocus={() => setFocusedInput('name')}
            onBlur={() => setFocusedInput(null)}
          />
          <Text style={styles.hintText}>
            This will be displayed on the storefront
          </Text>
        </View>

        {/* Slug (URL-friendly name) */}
        <View style={styles.inputGroup}>
          <View style={styles.labelContainer}>
            <Feather name="link" size={16} color={C.cyan} />
            <Text style={styles.label}>Slug (URL) *</Text>
          </View>
          
          <View style={styles.slugContainer}>
            <View style={styles.slugPrefix}>
              <Text style={styles.slugPrefixText}>store.com/category/</Text>
            </View>
            <TextInput
              style={[getInputStyle('slug'), styles.slugInput]}
              placeholder="mens-fashion"
              placeholderTextColor={C.textMuted}
              value={slug}
              onChangeText={handleSlugChange}
              onFocus={() => setFocusedInput('slug')}
              onBlur={() => setFocusedInput(null)}
              autoCapitalize="none"
              autoCorrect={false}
            />
          </View>
          
          <View style={styles.slugActions}>
            <TouchableOpacity 
              style={styles.slugAutoBtn} 
              onPress={handleSlugAuto}
              activeOpacity={0.7}
            >
              <Feather name="zap" size={14} color={C.cyan} />
              <Text style={styles.slugAutoText}>Auto-generate from name</Text>
            </TouchableOpacity>
          </View>
          
          <Text style={styles.hintText}>
            Used in the URL: yourstore.com/category/{slug || 'category-name'}
          </Text>
        </View>

        {/* Category Image Upload */}
        <View style={styles.inputGroup}>
          <View style={styles.labelContainer}>
            <Feather name="image" size={16} color={C.accentGreen} />
            <Text style={[styles.label, { color: C.accentGreen }]}>Category Image</Text>
          </View>
          <View style={styles.imageUploadWrapper}>
            <ImageUploader
              images={images}
              onImagesChange={setImages}
              maxImages={1}
              title="Upload Category Image"
            />
          </View>
          <Text style={styles.hintText}>
            Recommended: 400 x 400 pixels transparent background
          </Text>
        </View>

        {/* Slug Preview Card */}
        {slug && (
          <View style={styles.previewCard}>
            <LinearGradient
              colors={[C.surface, C.surfaceAlt]}
              style={styles.previewGradient}
            >
              <View style={styles.previewHeader}>
                <Feather name="eye" size={14} color={C.cyan} />
                <Text style={styles.previewTitle}>Preview</Text>
              </View>
              <View style={styles.previewUrl}>
                <Text style={styles.previewUrlLabel}>Category URL:</Text>
                <Text style={styles.previewUrlValue}>
                  yourstore.com/category/{slug}
                </Text>
              </View>
              <View style={styles.previewBadge}>
                <Feather name="check-circle" size={12} color={C.accentGreen} />
                <Text style={styles.previewBadgeText}>SEO Friendly URL</Text>
              </View>
            </LinearGradient>
          </View>
        )}

        {/* Action Buttons */}
        <View style={styles.buttonContainer}>
          <TouchableOpacity 
            style={styles.cancelButton} 
            onPress={onCancel} 
            disabled={loading}
            activeOpacity={0.7}
          >
            <LinearGradient
              colors={[C.surfaceAlt, C.surfaceAlt]}
              style={styles.cancelGradient}
            >
              <Feather name="x" size={18} color={C.textSecondary} />
              <Text style={styles.cancelButtonText}>Cancel</Text>
            </LinearGradient>
          </TouchableOpacity>
          
          <TouchableOpacity 
            style={styles.submitButton} 
            onPress={handleSubmit} 
            disabled={loading}
            activeOpacity={0.7}
          >
            <LinearGradient
              colors={[C.blue2, C.cyan]}
              start={{ x: 0, y: 0 }}
              end={{ x: 1, y: 0 }}
              style={styles.submitGradient}
            >
              {loading ? (
                <ActivityIndicator color={C.bg} size="small" />
              ) : (
                <>
                  <Feather name={isEditing ? "check-circle" : "plus-circle"} size={18} color={C.bg} />
                  <Text style={styles.submitButtonText}>
                    {isEditing ? 'Update Category' : 'Create Category'}
                  </Text>
                </>
              )}
            </LinearGradient>
          </TouchableOpacity>
        </View>

        {/* Help Section */}
        <View style={styles.helpSection}>
          <LinearGradient
            colors={[C.surface, C.surfaceAlt]}
            style={styles.helpCard}
          >
            <View style={styles.helpHeader}>
              <Feather name="help-circle" size={16} color={C.accentOrange} />
              <Text style={styles.helpTitle}>Tips for good category names</Text>
            </View>
            <View style={styles.helpList}>
              <View style={styles.helpItem}>
                <View style={styles.helpDot} />
                <Text style={styles.helpText}>Keep it short and descriptive (2-3 words)</Text>
              </View>
              <View style={styles.helpItem}>
                <View style={styles.helpDot} />
                <Text style={styles.helpText}>Use keywords customers might search for</Text>
              </View>
              <View style={styles.helpItem}>
                <View style={styles.helpDot} />
                <Text style={styles.helpText}>Avoid special characters and numbers</Text>
              </View>
              <View style={styles.helpItem}>
                <View style={styles.helpDot} />
                <Text style={styles.helpText}>Be consistent with your naming convention</Text>
              </View>
            </View>
          </LinearGradient>
        </View>
      </View>
    </ScrollView>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: C.bg,
  },
  contentContainer: {
    paddingBottom: 40,
  },
  
  // Header Section
  header: {
    alignItems: 'center',
    paddingVertical: 30,
    paddingHorizontal: 20,
    borderBottomLeftRadius: 30,
    borderBottomRightRadius: 30,
    marginBottom: 20,
    overflow: 'hidden',
  },
  headerIcon: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: 'rgba(0,229,255,0.15)',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 16,
    borderWidth: 1,
    borderColor: C.cyan + '30',
  },
  title: {
    fontSize: 24,
    fontWeight: '800',
    color: C.white,
    marginBottom: 8,
    textAlign: 'center',
  },
  subtitle: {
    fontSize: 13,
    color: C.blue4,
    textAlign: 'center',
    marginBottom: 12,
  },
  infoBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: 'rgba(0,229,255,0.15)',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 20,
    marginTop: 8,
  },
  infoBadgeText: {
    fontSize: 12,
    color: C.cyan,
    fontWeight: '500',
  },
  
  // Form Section
  formSection: {
    paddingHorizontal: 16,
  },
  inputGroup: {
    marginBottom: 20,
  },
  labelContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 8,
  },
  label: {
    fontSize: 14,
    fontWeight: '600',
    color: C.textPrimary,
  },
  input: {
    borderWidth: 1,
    borderColor: C.border,
    borderRadius: 12,
    padding: 14,
    fontSize: 14,
    color: C.textPrimary,
    backgroundColor: C.surface,
  },
  inputFocused: {
    borderColor: C.cyan,
    borderWidth: 2,
    shadowColor: C.cyan,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 4,
  },
  hintText: {
    fontSize: 11,
    color: C.textMuted,
    marginTop: 6,
    marginLeft: 4,
  },
  
  // Slug Section
  slugContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: C.surface,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: C.border,
    overflow: 'hidden',
  },
  slugPrefix: {
    backgroundColor: C.surfaceAlt,
    paddingHorizontal: 12,
    paddingVertical: 14,
    borderRightWidth: 1,
    borderRightColor: C.border,
  },
  slugPrefixText: {
    fontSize: 12,
    color: C.textMuted,
  },
  slugInput: {
    flex: 1,
    borderWidth: 0,
    margin: 0,
    paddingHorizontal: 12,
  },
  slugActions: {
    marginTop: 8,
    alignItems: 'flex-start',
  },
  slugAutoBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingVertical: 6,
    paddingHorizontal: 10,
    borderRadius: 8,
    backgroundColor: 'rgba(0,229,255,0.1)',
  },
  slugAutoText: {
    fontSize: 12,
    color: C.cyan,
    fontWeight: '500',
  },
  
  // Image Upload
  imageUploadWrapper: {
    marginTop: 4,
  },
  
  // Preview Card
  previewCard: {
    marginBottom: 24,
    borderRadius: 16,
    overflow: 'hidden',
  },
  previewGradient: {
    padding: 16,
    borderWidth: 1,
    borderColor: C.border,
  },
  previewHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginBottom: 12,
    paddingBottom: 10,
    borderBottomWidth: 1,
    borderBottomColor: C.border,
  },
  previewTitle: {
    fontSize: 12,
    fontWeight: '600',
    color: C.textPrimary,
  },
  previewUrl: {
    marginBottom: 10,
  },
  previewUrlLabel: {
    fontSize: 11,
    color: C.textMuted,
    marginBottom: 4,
  },
  previewUrlValue: {
    fontSize: 13,
    fontWeight: '600',
    color: C.cyan,
    fontFamily: 'monospace',
  },
  previewBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginTop: 8,
    paddingTop: 8,
    borderTopWidth: 1,
    borderTopColor: C.border,
  },
  previewBadgeText: {
    fontSize: 11,
    color: C.accentGreen,
    fontWeight: '500',
  },
  
  // Button Container
  buttonContainer: {
    flexDirection: 'row',
    gap: 12,
    marginBottom: 24,
  },
  cancelButton: {
    flex: 1,
    borderRadius: 12,
    overflow: 'hidden',
  },
  cancelGradient: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 14,
    gap: 8,
    borderWidth: 1,
    borderColor: C.border,
  },
  cancelButtonText: {
    color: C.textSecondary,
    fontSize: 15,
    fontWeight: '600',
  },
  submitButton: {
    flex: 1.5,
    borderRadius: 12,
    overflow: 'hidden',
  },
  submitGradient: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 14,
    gap: 8,
  },
  submitButtonText: {
    color: C.bg,
    fontSize: 15,
    fontWeight: '700',
  },
  
  // Help Section
  helpSection: {
    marginTop: 8,
    marginBottom: 20,
  },
  helpCard: {
    borderRadius: 16,
    padding: 16,
    borderWidth: 1,
    borderColor: C.border,
  },
  helpHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 12,
    paddingBottom: 10,
    borderBottomWidth: 1,
    borderBottomColor: C.border,
  },
  helpTitle: {
    fontSize: 13,
    fontWeight: '600',
    color: C.textPrimary,
  },
  helpList: {
    gap: 10,
  },
  helpItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  helpDot: {
    width: 4,
    height: 4,
    borderRadius: 2,
    backgroundColor: C.cyan,
  },
  helpText: {
    fontSize: 12,
    color: C.textSecondary,
    flex: 1,
  },
});
